# Generated by Django 2.1.4 on 2018-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
